blueprint:
  name: Door Light Control
  description: Turn on a light when a door is opened and turn it off when the door is closed.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: The Zigbee2MQTT door sensor.
      selector:
        entity:
          domain: binary_sensor
    light:
      name: Light
      description: The light to control.
      selector:
        entity:
          domain: light
    light_color_temp:
      name: Light Color Temperature
      description: The color temperature of the light in Kelvins.
      default: 5000
      selector:
        number:
          min: 2500
          max: 6500
          unit_of_measurement: K
    light_brightness:
      name: Light Brightness
      description: The brightness of the light (0-100%).
      default: 100
      selector:
        number:
          min: 0
          max: 100

trigger:
  - platform: state
    entity_id: !input door_sensor

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'on'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness: "{{ (input.light_brightness | int * 255 / 100) | int }}"
              color_temp: "{{ input.light_color_temp | int }}"
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'off'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light
